# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sd4Mchp3MXTIFaXo3DiMLMbDuvPW_v2G
"""

#SOLAR PANEL POWER OUTPUT SIMULATION
import numpy as np
solar_irradiance=np.array([100,1000])# w/m^2
temperature=np.array([25,30])# c
efficiency=np.array([0.8,0.9])
area=np.array([10,20])# m^2
power_output=solar_irradiance*temperature*efficiency*area
print(power_output)
import matplotlib.pyplot as plt
current=[2,4,6,8]
voltage=[12,14,16,18]
power=[10,20,30,40]
plt.plot(current,voltage,marker='s')
plt.xlabel('current(A)')
plt.ylabel('voltage(V)')
plt.title("voltage vs current curve")
plt.show()
plt.plot(power,voltage,marker='s')
plt.xlabel('power(w)')
plt.ylabel('voltage(V)')
plt.title("voltage vs power curve")
plt.show()